[package]
name = "d3Storage"
version = "1.5.0"
description = "Decentralized Distributed Data (D3) Storage"
repository = "https://github.com/ragpatel8742/d3storage"
keywords = [ ]
license = "MIT"

[dependencies]
base = "0.11.1"
rand = "https://github.com/aviate-labs/rand.mo#v0.2.3"
ulid = "https://github.com/aviate-labs/ulid.mo#v0.1.3"
map = "https://github.com/ZhenyaUsenko/motoko-hash-map#v9.0.1"
httpParser = "https://github.com/NatLabs/http-parser.mo#v0.1.2@27cba8ed0d39387e0fb660f65909ffe2a7d54413"
vector = "0.4.1"
stableheapbtreemap = "1.5.0"